# NodeJS Version 20
FROM node:20.14-buster-slim
# Copy Dir
COPY . ./app
# Work to Dir
WORKDIR /app
# Install Node Package
RUN npm install 
# Set Env
ENV NODE_ENV production
EXPOSE 3000
# Cmd script
CMD ["npm", "run", "start"]
